id = "aura"
name = "Aura"
version = "0.1.0"
schema_version = 1
authors = ["Hannah Harrisonn <hannah@harrisonn.dev>"]
description = "Aura language support for Zed"
repository = "https://github.com/nahharris/aura-zed"

[grammars.aura]
repository = "https://github.com/nahharris/tree-sitter-aura"
rev = "084596da462974218545e319acbf7b18b52e7a77"
