name = "Aura"
grammar = "aura"
path_suffixes = ["aura"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
tab_size = 4
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]

word_characters = ["_"]

[overrides.string]
completion_query_characters = ["$"]
